
export const rows = [
    {
        id: 1,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'user',
    }, {
        id: 2,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'user',
    }, {
        id: 3,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'Admin',
    }, {
        id: 4,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'Admin',
    }, {
        id: 5,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 6,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 7,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 8,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 9,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 10,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 11,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 12,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 13,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 14,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 15,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 16,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 17,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 18,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 19,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },{
        id: 20,
        name: 'amal ibrahim',
        email: 'World@fhxdthxfd',
        age: 30,
        phone: '01276925856',
        access: 'manager',
    },

];
